import { ScopeType, SCOPES } from "./scopes";

export const ROLE_SCOPES: Record<string, ScopeType[]> = {
    admin: [
        SCOPES.READ_USER,
        SCOPES.MANAGE_USER,
        SCOPES.READ_LOGIN_ACTIVITY,

        SCOPES.READ_CLUB,
        SCOPES.MANAGE_CLUB,

        SCOPES.READ_MEMBERSHIP,
        SCOPES.MANAGE_MEMBERSHIP,

        SCOPES.READ_NOTICE,
        SCOPES.MANAGE_NOTICE,

        SCOPES.READ_ACTIVITY,
        SCOPES.MANAGE_ACTIVITY,

        SCOPES.READ_EVENT,
        SCOPES.MANAGE_EVENT,

        SCOPES.READ_EVENT_CATEGORY,
        SCOPES.MANAGE_EVENT_CATEGORY,
        SCOPES.READ_FORM,
        SCOPES.MANAGE_FORM,

        SCOPES.READ_FORM_RESPONSE,
        SCOPES.VERIFY_FORM_RESPONSE,

        SCOPES.READ_CERTIFICATE,
        SCOPES.ISSUE_CERTIFICATE,

        SCOPES.READ_BLOG,
        SCOPES.MANAGE_BLOG,

        SCOPES.READ_BLOG_COMMENT,
        SCOPES.MANAGE_BLOG_COMMENT,
    ],

    mentor: [
        SCOPES.READ_CLUB,
        SCOPES.READ_MEMBERSHIP,
        SCOPES.MANAGE_MEMBERSHIP,
        SCOPES.READ_EVENT,
        // SCOPES.MANAGE_EVENT,
        SCOPES.READ_ACTIVITY,
        SCOPES.MANAGE_ACTIVITY,
        SCOPES.READ_BLOG,
        SCOPES.MANAGE_BLOG,
        SCOPES.CREATE_BLOG_COMMENT,
        SCOPES.MANAGE_BLOG_COMMENT,
    ],

    alumni: [
        SCOPES.READ_CLUB,
        SCOPES.READ_EVENT,
        SCOPES.READ_ACTIVITY,
        SCOPES.READ_BLOG,
        SCOPES.CREATE_BLOG,
        SCOPES.CREATE_BLOG_COMMENT,
    ],

    dcs: [
        SCOPES.READ_USER,
        SCOPES.READ_STUDENT,
        SCOPES.VERIFY_FORM_RESPONSE,
    ],

    other: [
        SCOPES.READ_CLUB,
        SCOPES.READ_EVENT,
        SCOPES.READ_BLOG,
        SCOPES.CREATE_BLOG_COMMENT,
    ],
};


